kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-aws

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP

  - role: worker   # Simulates t3.micro node
    labels:
      cloud: aws   # Correct way to apply node label

networking:
  apiServerAddress: "127.0.0.1"
  podSubnet: "10.244.0.0/16"  # AWS-like
