kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-azure

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30001
        hostPort: 30001
        protocol: TCP

  - role: worker    # Simulates Standard_B2s node
    labels:
      cloud: azure  # Correct way

networking:
  apiServerAddress: "127.0.0.1"
  podSubnet: "10.245.0.0/16"   # Azure-like
